steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/devtalles-432023/image-registry-talles/products-ms",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/devtalles-432023/image-registry-talles/products-ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
